# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision :docker
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provision :file, source: "file.txt", destination:"file.txt"
  config.vm.provision :file, source: "dir1", destination:"dir1"

  config.vm.define "server-1" do |dockerserver|
    dockerserver.vm.network "private_network", ip: '192.168.33.30'
    dockerserver.vm.hostname = "dockerserver"    
    dockerserver.vm.provision :file, source:"../docker/docker-compose.ci.yaml", destination:"docker-compose.yaml"
    dockerserver.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yaml", run:"always"     
  end
end
