# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision :docker
  config.vm.provision :docker_compose

  config.vm.define "server-1" do |dockerserver|
    dockerserver.vm.network "private_network", ip: '192.168.33.30'
    dockerserver.vm.hostname = "dockerserver"    
    dockerserver.vm.provision :file, source:"../docker/docker-compose.ci.yaml", destination:"docker-compose.yaml"
    dockerserver.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yaml", run:"always"     
    dockerserver.vm.provision :shell, inline:"sudo chmod 777 /var/run/docker.sock && sudo chmod 777 /usr/bin/docker && sudo chmod 777 /.local"
    dockerserver.vm.provision :shell, inline:"sudo chmod 777 /usr/local/bin/docker-compose"
  end
end

